server:
  port: 20087
spring:
    datasource:
      url: jdbc:mysql://mysql.sinfonia.heiha.com:3306/test?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: test
      password: 123456
mybatis:
  mapper-locations: classpath:sql/mapper/*Mapper.xml
eureka:
  instance:
    hostname: wechat.sinfonia.heiha.com
  client:
    serviceUrl:
      defaultZone: http://eureka.sinfonia.heiha.com:20089/eureka/